### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by gr3ger** [averne/Fizeau#10]
Error 0xf601 (2001-0123)
System version: 10.1.0
Atmos version: 0.14.1

If there's any more info you need just let me know!

**Comment by averne** [comment]
Do you have any other sysmodule active?

**Comment by averne** [comment]
Okay, after booting with fusee-primary instead of hekate, I get this error. Do you also use fusee-primary?

**Comment by gr3ger** [comment]
Yep, I'm using fusee primary as well :)
And yes, the OVL sysmodule is loaded as well.

**Comment by averne** [comment]
I pushed a fix ealier today for this issue, could you confirm it works for you?

**Comment by gr3ger** [comment]
Yep, after updating and rebooting it seems to work like a charm :)
Great work!
