### ISSUE TITLE
Controls messed up

### ISSUE THREAD

**Issue by ImportTaste** [averne/Fizeau#12]
I'm on Atmosphere 0.14.1, and while everything seems to work, the non-touchscreen controls don't match up to the instructions.

L does nothing. R does the same thing as X, and while the 'D-Pad' on the left will control every other slider, it does not affect the Brightness slider.

**Comment by averne** [comment]
Which version of the program are you using? It seems you are using 1.x.
I have recently "released" a new vastly improved version that does actual color correction, without the needing an overlay.
However I'm in kind of an awkward position as I haven't been able to test it on an external display yet, so I can't officially release that new version. However I haven't received reports of anything being broken.

Could you try installing it? 
[Fizeau-2.0.0-f94bccd.zip](https://github.com/averne/Fizeau/files/5129203/Fizeau-2.0.0-f94bccd.zip)

**Comment by ImportTaste** [comment]
It seems to work well enough... though I don't understand the new gamma values. Is the system default supposed to be 2.40? Like, if I wanted to establish a baseline of all the Nintendo Switch defaults, what would it be at?

**Comment by averne** [comment]
Default gamma would be 2.4, indeed. The default config which is provided with the zip doesn't change any of the correction features.
If you mess up you can reset the profile, which sets all values (except times) back to their defaults.
