### ISSUE TITLE
Fatal error on 10.1.0 when opening the app

### ISSUE THREAD

**Issue by begarage** [averne/Fizeau#13]
![IMG_20200908_104505](https://user-images.githubusercontent.com/70934301/92436336-0e0e7780-f1c2-11ea-9206-0d92dc84d824.jpg)

Please help and thank you for sharing such apps with the community. People like you are gold to us all 🥇

**Comment by averne** [comment]
Did you install using the homebrew app store?

**Comment by begarage** [comment]
No, I installed it via the releases here. I also noticed that in the sysmodules folder of tesla, fizeau shows that I need to restart for it to work but I've already done so, a lot of times. Also, it doesn't turn on if I try to toggle it but I can toggle auto start but it still doesn't work

**Comment by begarage** [comment]
Got it to work. Re-downloaded the file and re-added the folders and voila- working like a charm. Thank you!
