### ISSUE TITLE
Fizeau

### ISSUE THREAD

**Issue by zeush83** [averne/Fizeau#14]
Hi fizeau no working en atmosphear 0.14.3

**Comment by averne** [comment]
It needs an update to libstratosphere for the new AMS version, I'll do that tomorrow.

**Comment by zeush83** [comment]
Thanks very much

**Comment by zeush83** [comment]
Good morning I wanted to know how I will know when you update the file. Sorry if the question bothers you but I am new to these things and the truth is this application is incredible. Thank you

**Comment by averne** [comment]
This should be fixed as of the latest commit. I'm waiting for confirmation and I'll push a release.
[Fizeau-2.0.1-1a989f6.zip](https://github.com/averne/Fizeau/files/5241086/Fizeau-2.0.1-1a989f6.zip)

**Comment by zeush83** [comment]
> Esto debería arreglarse a partir de la última confirmación. Estoy esperando confirmación y presionaré un comunicado.
> [Fizeau-2.0.1-1a989f6.zip](https://github.com/averne/Fizeau/files/5241086/Fizeau-2.0.1-1a989f6.zip)

No working

**Comment by zeush83** [comment]
![16003673769891795002545](https://user-images.githubusercontent.com/71411639/93512541-bb9d2b80-f924-11ea-93c8-24b75976427d.jpg)

**Comment by averne** [comment]
Works fine on my machine.
Can you upload the error report at `/atmosphere/fatal_errors/report_000[...]9a8ceff.bin`?

**Comment by zeush83** [comment]
i load atmosphere with fuse primary

**Comment by zeush83** [comment]
> Funciona bien en mi máquina.
> ¿Puede cargar el informe de errores en `/atmosphere/fatal_errors/report_000[...]9a8ceff.bin`?

How can I do that 😅

**Comment by averne** [comment]
Take out the sd card from your switch, insert it in your computer, navigate to that file, then drag & drop it to the text box here.

**Comment by zeush83** [comment]
[01600289064_0100000000000f12.log](https://github.com/averne/Fizeau/files/5241466/01600289064_0100000000000f12.log)

**Comment by zeush83** [comment]
He will not let me alone I could send that file and I do not know if it will be worth it. Anyway for his work and patience

**Comment by averne** [comment]
1. Update to AMS 0.14.4. It will crash on other versions.
2. Do you have other sysmodules running?

**Comment by zeush83** [comment]
[report_0000000009a8ceff.zip](https://github.com/averne/Fizeau/files/5241583/report_0000000009a8ceff.zip)

**Comment by zeush83** [comment]
Thanx work 😁😁😁😁

**Comment by zeush83** [comment]
![16003733110251346425479](https://user-images.githubusercontent.com/71411639/93522811-58b29100-f932-11ea-8159-ed6873682257.jpg)
Finaly work thanks so much verne you rock o en español erer un gran portento para la scene

**Comment by zeush83** [comment]
Only edizon

**Comment by JrRadiant** [comment]
@zeush83 What kind of OFW do you have? Is it 10.1.0 OR 10.2.0 ??

**Comment by zeush83** [comment]
10.2.0

**Comment by zeush83** [comment]
![16003743004061980595311](https://user-images.githubusercontent.com/71411639/93524352-acbe7500-f934-11ea-9aa4-94c76bf5cf65.jpg)

**Comment by zeush83** [comment]
![1600374350752319966904](https://user-images.githubusercontent.com/71411639/93524426-c495f900-f934-11ea-978d-aeb5a18d47d7.jpg)

**Comment by JrRadiant** [comment]
Thank you.
