### ISSUE TITLE
crashes seemingly for no reason when trying to run on 10.2.0

### ISSUE THREAD

**Issue by AlexS2412** [averne/Fizeau#15]
![20200917_004100](https://user-images.githubusercontent.com/14182708/93421973-b25a8300-f880-11ea-80a2-b4cb79077ac5.jpg)

**Comment by JrRadiant** [comment]
Can confirm that. ^

**Comment by averne** [comment]
Should be fixed as of the latest commit. Can someone confirm?

**Comment by JrRadiant** [comment]
> Should be fixed as of the latest commit. Can someone confirm?
> [Fizeau-2.0.1-1a989f6.zip](https://github.com/averne/Fizeau/files/5241059/Fizeau-2.0.1-1a989f6.zip)

Doesn't work, yellow text PANIC occurred — i'm on OFW 10.2.0, AMS 0.14.3:

TitleID: 01000000000F12
Error: std::abort (0xFFE)

Here's the dump: 
[report_09f162cc.zip](https://github.com/averne/Fizeau/files/5241209/report_09f162cc.zip)

**Comment by averne** [comment]
Seems like it's aborting during init. The thing is, it's working fine on my machine so I'm debugging this blindly...

**Comment by JrRadiant** [comment]
How we can help?

**Comment by averne** [comment]
Are you on AMS 0.14.4?
It's crashing on the AMS API check, because it expects the runtime version to be higher or equal to 0xe04 (ie 0.14.4, `0xe04 == (0 << 16) | (14 << 8) | (4 << 0)`).
![image](https://user-images.githubusercontent.com/45773016/93515805-78918700-f929-11ea-978e-00c2fdaa253f.png)

**Comment by JrRadiant** [comment]
I was on 0.14.3. Now I'm at 0.14.4, no errors on boot BUT panic occurred when I open the Fizeau
[report_023caaa8c.zip](https://github.com/averne/Fizeau/files/5241440/report_023caaa8c.zip)
 homebrew:

010000000000F12
ERROR: IABRT (0x100)

Here's the REPORT:

**Comment by averne** [comment]
This one is stranger. The sysmodule is trying to exit, which shouldn't happen under normal conditions. Do you have other sysmodules running?

**Comment by JrRadiant** [comment]
No, I've exactly my old setup from 10.1.0 @ Atmosphere 0.14.2, when everything was all right..

**Comment by averne** [comment]
Try again with a clean install. For now I'm assuming something is wrong with your setup, see https://github.com/averne/Fizeau/issues/14#issuecomment-694472822

**Comment by JrRadiant** [comment]
Tried again with fixed archive bit, and it works. Thanks!

**Comment by averne** [comment]
Thanks, I had no idea that could cause issues for sysmodules.
