### ISSUE TITLE
Can't make the temperature colder

### ISSUE THREAD

**Issue by airchase** [averne/Fizeau#16]
Unless I'm missing something, I'm unable to make the color temperature colder on my switch, only warmer.

My switch is on the older side, and suffers from a slightly yellower display. I saw this [Youtube video](https://www.youtube.com/watch?v=UcM23cwLv8E) which showed an RGB slider in the Fizeau app which I thought would do the trick, but those options seem to have been removed in the latest version.

I've set the color temperature in the app to as cold as it can go (all the way to the right), however this temperature appears to be the default native temperature and make no difference in terms of cooling off the screen.

Is there a reason the RGB sliders have been removed from the latest version of the app? Is there another way to accomplish what I'm after in this new version?

Thanks!

**Comment by averne** [comment]
Fizeau was rewritten in version 2.0 to take advantage of a GPU feature to achieve actual color correction, instead of relying on an overlay to modify on-screen colors (the overlay was effectively trashing darker pixels, since they would get blended with brighter colors).
Along with this I removed the ability to control separate color channels, since I thought it was no longer useful. Instead, I moved to something closer to what's available on my desktop (temperatures ranging from 1000-6500K, 6500K being the [standard D65 illuminant](https://en.wikipedia.org/wiki/Illuminant_D65)).

I removed that restriction in commit 27ab650. Colder colors up to 10'000K are now locked behind a checkbox in the app, so as to make it less confusing for people who don't care about the feature.

**Comment by airchase** [comment]
Awesome! I'm sorry for asking what is probably a stupid question, but how do I access the latest changes you made? I tried downloading the latest release available on here, but I can't seem to find any checkbox enabling the wider color temperature settings. Can't wait to try it out.

**Comment by averne** [comment]
I haven't made a new release yet because I'm working on something else beforehand, but you can access the CI build here: https://github.com/averne/Fizeau/suites/1430677044/artifacts/24109265

**Comment by airchase** [comment]
Right on, works perfectly. Out of curiosity, have you considered having an option to have Fizeau "launch" at startup automatically? I'm not even sure if that's possible, but I think the Tesla overlay seems to do it somehow.

Not a huge deal if it's not, just an idea.

**Comment by averne** [comment]
Technically this is possible, but that would require adding code in the sysmodule (~daemon) to read the config file and parse it, and I'd like to keep it as slim as possible (the system memory pool of the Switch OS is quite limited so I'm wary of bloating it). 
When booting any of the clients (application or overlay), the config gets read and applied, but in reality the sysmodule was already running, just doing nothing as it didn't receive input yet. 
I think starting a client after booting the console is a small enough inconvenience (especially after the addition of the overlay) that I can leave it as is.

**Comment by airchase** [comment]
Okay makes sense. It's not an inconvenience for me at all whatsoever, I'm just trying to make everything as simple as possible for my girlfriend (who I'll be gifting the switch for her birthday next week). Got autorcm, and autoboot in Hekate working perfectly, and wondered if there was a way to get this streamlined as well. Maybe it's something that could enable with a checkbox as well for people that'd like the feature?

If it's too cumbersome though, that's understandable. Loving the app so far, keep up the good work.

**Comment by averne** [comment]
If you're still interested in this, I wrote a small stub that launches the modules and applies the config. 
See https://github.com/averne/Fizeau/releases/tag/v2.1.0
