### ISSUE TITLE
Error 0x1 (2001-0000) running under Atmosphere 0.16.2/Hekate 5.5.1

### ISSUE THREAD

**Issue by tildebyte** [averne/Fizeau#20]
Atmos: 0.16.2-master-d7b14f48+hbl-2.4.0+hbmenu-3.4.0
Hekate: ctcaer_5.5.1_Nyx_0.9.7
OFW: 10.2.0
![IMG_0095](https://user-images.githubusercontent.com/337875/102843335-fce72080-43d6-11eb-99ca-8736afee8720.png)

¯\\\_(ツ)_/¯

"Everything else" seems fine after today's Atmos/Hekate upgrade. I manually removed (==1.x) and installed (2.1.2) Fizeau.

**Comment by averne** [comment]
This means the service isn't running, please check your /switch/atmosphere/contents folder?

**Comment by tildebyte** [comment]
> please check your /switch/atmosphere/contents folder

What am I looking for?

**Comment by tildebyte** [comment]
Got it. "Reinstalled" from the zip, overwriting all, and everything's fine now. Must've been an old/stale file...? Dunno.
