### ISSUE TITLE
Crashes on switch lite atmosphere 0.17

### ISSUE THREAD

**Issue by mustafapx** [averne/Fizeau#22]
[report_000000002fba94b2.zip](https://github.com/averne/Fizeau/files/5790503/report_000000002fba94b2.zip)
Whenever i try to activate it the switch freezes for few seconds then crash
here is the error log

**Comment by averne** [comment]
Can you please check that you config (/switch/Fizeau/config.ini) isn't corrupted? It works for me on AMS 0.17.

**Comment by mustafapx** [comment]
> Can you please check that you config (/switch/Fizeau/config.ini) isn't corrupted? It works for me on AMS 0.17.

Its fine i deleted it but same error i also tried a freah sdcard just in case same crashing error

**Comment by averne** [comment]
Not sure then. Several people have reported issue with Lite units, but unfortunately I can't debug those since I don't have one myself.

**Comment by mustafapx** [comment]
> Not sure then. Several people have reported issue with Lite units, but unfortunately I can't debug those since I don't have one myself.

Isn there anything i can help with a way to get you logs or test some solutions that you might have :(

**Comment by averne** [comment]
[Fizeau-2.1.2-a12ebb2-dirty.zip](https://github.com/averne/Fizeau/files/5791676/Fizeau-2.1.2-a12ebb2-dirty.zip)
That's a shot in the dark, but could you try this build (and upload the error report if it fails)?

**Comment by mustafapx** [comment]
> [Fizeau-2.1.2-a12ebb2-dirty.zip](https://github.com/averne/Fizeau/files/5791676/Fizeau-2.1.2-a12ebb2-dirty.zip)
> That's a shot in the dark, but could you try this build (and upload the error report if it fails)?

Same crash
 here is tje report

**Comment by mustafapx** [comment]
So i noticed something that might be useful
When i hit the correction checkbox the screen brightness gose downa bit ( becomes dimmer ) after the freezes and then in few seconds a white screen show up for 2 seconds then crashes

**Comment by averne** [comment]
So, this error actually comes from AMS's fatal module, which is aborting for some reason.
There should be a report in your atmosphere/fatal_errors or atmosphere/crash_reports, that logged the real error coming from my code.

**Comment by mustafapx** [comment]
here
