### ISSUE TITLE
Feature Request: Add a toggle to follow HOS brightness level and dimming timeout settings

### ISSUE THREAD

**Issue by renA21** [averne/Fizeau#23]
~~I've encountered some issues in which that the backlight is not dimmed when auto-sleep is enabled, it seems that the backlight and color correction is readjusted (when auto-sleep dimming is triggered) to the set brightness profile settings when Fizeau is active.~~

My setup:

Fizeau version: 2.1.2-9449f24
HOS: 11.0.1
Atmosphere: 0.17.0

EDIT:

I just found out that Fizeau has an independent option for dimming timeout. Would you consider adding a toggle for Fizeau to follow HOS' settings for brightness level and dimming timeout?

**Comment by averne** [comment]
You can disable it by setting the dimming timeout to 0 on Fizeau's side.
However the problem with this is that when HOS applies dimming to the screen Fizeau will override it shortly after, effectively this completely disables dimming in docked mode, and only enables backlight dimming in handheld.
That's the reason I added an option to handle dimming ourselves.
