### ISSUE TITLE
Chainloader version doesn't work with the latest AMS 0.19.3

### ISSUE THREAD

**Issue by JrRadiant** [averne/Fizeau#29]
Hello again, dear averne!..

Please update your Fizeau Chainloader version to support the very new AMS 0.19.**_3_**, for now the latest build is panicked again with std::abort 0xffe.

Thanks in advance!

**Comment by Ammako** [comment]
There was a commit yesterday to fix 0.19.3 compatibility, but the build failed or something

https://github.com/averne/Fizeau/actions/runs/836562223

**Comment by averne** [comment]
https://github.com/averne/Fizeau/releases/tag/v2.1.7
Should be good with this.

**Comment by JrRadiant** [comment]
@averne 
Works like a charm with OFW 12.0.2, AMS M.19.3, thank you again!.. I literally can't use my Switch AT ALL without your wonderful homebrew, many-many-many Thanks! :)

**Comment by averne** [comment]
No problem, thanks for testing!
