### ISSUE TITLE
add a tesla .ovl file for fizeau?

### ISSUE THREAD

**Issue by chaiaia** [averne/Fizeau#3]

**Comment by chaiaia** [comment]
there's a new program out on switch called tesla. it's an overlay based one, i believe it's L + something + down to open, they have an overlay hbmenu so far. it would be really cool to have fizeau on tesla, so we could change the colours and alpha in game.
https://gbatemp.net/threads/tesla-the-nintendo-switch-overlay-menu.557362/

**Comment by averne** [comment]
I'm aware of this. I'm working on something else at the moment but I think I'll take a look sometime. 
Also the API is moving a lot right now so I'd like to wait a bit before it stablizes.

**Comment by chaiaia** [comment]
> I'm aware of this. I'm working on something else at the moment but I think I'll take a look sometime.
> Also the API is moving a lot right now so I'd like to wait a bit before it stablizes.

thank you for replying so quick! i completely understand, thank you for considering :)

**Comment by averne** [comment]
Sorry, that's not possible for technical reasons (see https://github.com/averne/Fizeau/issues/5#issuecomment-601356891 for more details).
