### ISSUE TITLE
Disable at startup?

### ISSUE THREAD

**Issue by ncend** [averne/Fizeau#30]
Is there anyway to disable the filter at startup?
In my case it is auto start even when it reaches nintendo boot logo at startup.
I tried to turn it off (switch to inactive), but then when I reboot the switch it goes back to active.
Any suggestion will be appreciated. Thank you in advance.
Cheers.
![Screenshot_20210514-190134_Gallery](https://user-images.githubusercontent.com/11675631/118278921-b9f82780-b4f4-11eb-9bf4-8c9b0cbe62ea.jpg)

**Comment by ncend** [comment]
Atmosphere version: 0.19.2
HOS version: 12.0.1

**Comment by averne** [comment]
Thanks for the report, this should be fixed as of the latest commit. 
Here are the builds if you want to try it:
- [Fizeau-2.1.7-93148ea.zip](https://github.com/averne/Fizeau/files/6479629/Fizeau-2.1.7-93148ea.zip) 
- [Fizeau-chl-2.1.7-93148ea.zip](https://github.com/averne/Fizeau/files/6479633/Fizeau-chl-2.1.7-93148ea.zip)
