### ISSUE TITLE
Atmosphere 0.19.4 An error occurred

### ISSUE THREAD

**Issue by lowburger** [averne/Fizeau#31]
Hi, I report again Fizeau broke on new versions:

Fizeau 2.1.7
Atmosphere 0.19.4 with fusee-primary
Firmware 12.0.3

An error occurred: 0xf601 (2001-0123)

Thx

**Comment by Theguysayhi** [comment]
I would like to also bump for this!
Same error experienced.

**Comment by Ammako** [comment]
Fine here on 12.0.1/AMS 0.19.4, so it might be a 12.0.3 issue rather than an AMS issue.

I'm not using the chainloader though. It's possible that the chainloader could be broken while the regular one works.

**Comment by pixeltester** [comment]
> 
> 
> Fine here on 12.0.1/AMS 0.19.4, so it might be a 12.0.3 issue rather than an AMS issue.
> 
> I'm not using the chainloader though. It's possible that the chainloader could be broken while the regular one works.

Either that or you probably boot with hekate which works around this problem.

**Comment by averne** [comment]
Should be fixed in the latest release.
Hekate is indeed more lenient with firmware/AMS versions.
