### ISSUE TITLE
config.ini at ./config/Fizeau instead of ./switch/Fizeau

### ISSUE THREAD

**Issue by Ammako** [averne/Fizeau#32]
Hiya. How would you feel about storing the config at sdmc:/config/Fizeau instead of storing it in the /switch folder? Be cleaner that way if we could get more devs to put their config files there instead of everyone storing them alongside the .nro

It would be a little more convenient that way for users when updating too, because they could just copy/overwrite the /atmosphere and /switch folders to update, leaving /config untouched. Otherwise they have to go through the archive to extract and replace only the nro, and that's a bit of a hassle.

**Comment by averne** [comment]
I'm not against this in principle, but I think preserving backwards compatibility (ie checking for the old location) is important too.

**Comment by Ammako** [comment]
True. Shouldn't be too difficult to make it check both locations. Prioritizing the old location, of course.
