### ISSUE TITLE
toolbox.json in chl package + minor bug

### ISSUE THREAD

**Issue by FlyingBananaTree** [averne/Fizeau#36]
Some feedback:

- The toolbox.json should probably be removed from `0100000000000F12` in the chl release package and a new json created in `010000000000CF12` to manage the boot2.flag there. The sysmodules overlay does mark fizeau chl as 'off' but that's secondary to actually managing the boot2.flag I'd say.
 
- Attempting to launch the ovl if the fizeau sysmodule is not running silently crashes tesla until reboot, ideally an error message or something to inform the user that the sysmodule is not running would pop up instead as the nro homebrew does.

**Comment by averne** [comment]
>The toolbox.json should probably be removed from 0100000000000F12 in the chl release package and a new json created in 010000000000CF12 to manage the boot2.flag there. The sysmodules overlay does mark fizeau chl as 'off' but that's secondary to actually managing the boot2.flag I'd say.

The chl module actually terminates after launching the main sysmodule, so it's normal if it appears "off". If there is a way to make the toolbox ignore it I'll add that.

>Attempting to launch the ovl if the fizeau sysmodule is not running silently crashes tesla until reboot, ideally an error message or something to inform the user that the sysmodule is not running would pop up instead as the nro homebrew does.

Thanks for the report, as of 133f8283439142e775df61f14c0257c86161a994 the overlay just exits when the service is not active.

**Comment by FlyingBananaTree** [comment]
> 
> The chl module actually terminates after launching the main sysmodule, so it's normal if it appears "off". If there is a way to make the toolbox ignore it I'll add that.

Yes that makes sense, there's no way to do that I'm aware of but I don't think it matters much. If someone really wanted to know if Fizeau was running from the sysmodules overlay they could go ahead and create a second json at `0100000000000F12` just for that purpose, unnecessary bloat though and would probably just cause confusion if included by default.

> 
> Thanks for the report, as of [133f828](https://github.com/averne/Fizeau/commit/133f8283439142e775df61f14c0257c86161a994) the overlay just exits when the service is not active.

Great! Saturation is working amazingly well for me by the way, I tested both releases.

**Comment by averne** [comment]
>would probably just cause confusion if both are included by default in the chl package

I agree with this.
