### ISSUE TITLE
Fizeau 2.2.1 broke with ams 1.1.0 | ofw 13.0.0

### ISSUE THREAD

**Issue by cucholix** [averne/Fizeau#38]
It throws an error message when loading the overlay or when opening the nro app under ams 1.1.0 | ofw 13.0.0
![2021091916482000-AA3058B9B654D2E2A573FF95767EB51E](https://user-images.githubusercontent.com/16081693/133941036-89418c27-c064-45a4-a7b9-089780ebb8fd.jpg)
.
![2021091916484900-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/16081693/133941041-b231ea6a-c188-4cf4-8198-e66bf4f15e46.jpg)

**Comment by JrRadiant** [comment]
Same!
