### ISSUE TITLE
You need a toolbox.json

### ISSUE THREAD

**Issue by fennectech** [averne/Fizeau#4]
Create a file named toolbox.json next to the exefs.nsp   with this content

```
{
    "name"  : "Fizeau",
    "tid"   : "0100000000000F12",
    "requires_reboot": false
}
```

**Comment by averne** [comment]
What for?

**Comment by fennectech** [comment]
Toolbox.json lets tools like kosmos toolbox and sysmodule overlay pick it up and manage it.   Allowing users to enable and disable it on the fly.

**Comment by averne** [comment]
Thanks, I changed `requires_reboot` to `true` to prevent the kill/restart from messing with possibly dangling service handles.
