### ISSUE TITLE
Ams 1.2.4

### ISSUE THREAD

**Issue by Koognod** [averne/Fizeau#41]
Doesn't work on newest ams, crashes atmosphere on trying to enter the homebrew menu. Update again please🙏

**Comment by averne** [comment]
Works fine for me, can you check your setup?
What's your firmware version, are there any other sysmodule present?

**Comment by Koognod** [comment]
I figured It out thanks to your comment. I looked again at the error code and saw it referenced a different content folder than the one fizeau uses. Turns out it was a conflict between fizeau and sys-botbase. Deleted the folder for sys-botbase and fizeau worked fine. Thank you for your time and sorry about the false alarm. 😅
