### ISSUE TITLE
Micro stuttering in Pokémon BD with fizeau active

### ISSUE THREAD

**Issue by cucholix** [averne/Fizeau#45]
https://streamable.com/yguze7

As you can see in the clip when fizeau is activated a weird micro stuttering appears, it goes back to normal if you disable it.

It’s the first time I found a side effect when using fizeau, it’s worth mention Pokémon BD/SP uses Switch internal clock to set day or night time.

**Comment by averne** [comment]
That's pretty weird. I'm not sure it can come from the clock since Fizeau queries the `time` service only once at startup, then uses the `cntpct_el0` register to calculate the current timestamp.
I'll try to investigate.

**Comment by averne** [comment]
Also can you try making sure it persists between reboots, try with other sysmodules disabled, etc
Perhaps it looks clearer in person, but I honestly can't see a difference in you video

**Comment by cucholix** [comment]
Yes, it’s persistent between reboots, I thought it was atmosphere at first, but was disabling sysmodules one by one to isolate the problem. 

Will try to make another video indoor, I think the stuttering is worse there.

**Comment by averne** [comment]
Could you send me a save file with your character in the laggy zone?

**Comment by cucholix** [comment]
It’s in the whole game really, you will notice it at the start of the game in your room.

**Comment by averne** [comment]
Just tried this in ACNH and I can't reproduce. 
However I notive the overlay takes a very long time to start which is definitely not normal. Can you try this build? It's simply a build of master (the build I'm using), as there was a bugfix that solved this issue. I think it might also fix the stuttering.
[Fizeau.zip](https://github.com/averne/Fizeau/files/7976536/Fizeau.zip)

**Comment by cucholix** [comment]
Just tried the new build, and the issue persist…I think it has to do with internal clock access, it’s too coincidental that 3 games that has clock access exhibits this issue.
My config.ini has
Dusk start 00:00 - 00:00
Dusk end  00:00 - 00:00

Dawn start 00:00 - 00:00
Dusk ends 00:00 - 00:00

With newest build the overlay appears quickly though.

**Comment by averne** [comment]
What's the point of having the dawn and dusk times the same?

**Comment by cucholix** [comment]
> What's the point of having the dawn and dusk times the same?

I just want to play the game with the same image scheme independent from the time.

**Comment by averne** [comment]
Ok, this might be hitting an edge case. Does the issue persist when the dawn/dusk times are different?

**Comment by cucholix** [comment]
> Just tried this in ACNH and I can't reproduce.

Please try in docked mode

**Comment by cucholix** [comment]
> Ok, this might be hitting an edge case. Does the issue persist when the dawn/dusk times are different?

Tried with default times (as in package from release) and got the same issue.

**Comment by averne** [comment]
https://user-images.githubusercontent.com/45773016/152017350-449f9424-b15e-40ee-adc8-b03a56ccf756.mp4

**Comment by cucholix** [comment]
Weird, will do more test when I get home.
BTW I tried using the chainload version, but it doesn't activate upon reboot. Under system modules overlay it appears OFF and there's no way to turn it ON...

**Comment by cucholix** [comment]
Ok, some progress... deleting my config.ini and let fizeau generate a new one fixes the stuttering.
I recreated it from scratch, and it's working fine now, no stutter.

Attached both files, both generated through fizeau nro. 
[config.zip](https://github.com/averne/Fizeau/files/7982117/config.zip)

**Comment by averne** [comment]
I don't understand how saturation of all things can cause an issue. There's not even a "fast" codepath in case it's at 1.0 (ie has no effect), and it doesn't do anything special...
I'll try this evening on my Switch, see if I can reproduce. Could you send me a config file that triggers the issue?

About the chl version not working, you need to uncomment the first line in the config (active setting).

**Comment by cucholix** [comment]
[config.zip](https://github.com/averne/Fizeau/files/7985596/config.zip)
Here's the config that trigger stutter

**Comment by averne** [comment]
Following your message on reswitched, I wasn't testing in docked mode so that explains why I couldn't reproduce the issue. I'll take a look.

**Comment by averne** [comment]
Finally got the time to take a proper look at this. I believe it should be fixed as of the latest commit, you can try a CI build

**Comment by cucholix** [comment]
Fixed!
Thanks for your time, and commitment :)
