### ISSUE TITLE
Disabled after screen off

### ISSUE THREAD

**Issue by magarto** [averne/Fizeau#46]
Hi,

Eveytime I turn off the screen and on again, Fizeau is disabled.
Also, I installed last version of the chainloader but Fizeau is not applied automatically.

My Switch is first gen, with last version of Atmosphere (1.2.6) and firmware 13.2.0

Thanks for this great app.

**Comment by averne** [comment]
> I installed last version of the chainloader but Fizeau is not applied automatically
Check your config is the `active = true` line commented?

**Comment by magarto** [comment]
Yes it is.
I made a clean atmosphere install with some sys modules and it worked but after some tweaks (brightness and gamma) it stopped working again after reboot or screen off.
Is there any way to debug log it?

**Comment by averne** [comment]
There's no easy way to debug this, no. Can you share a list of sysmodules you have installed? It might either be some kind of conflict, or maybe you're exhausting the system memory pool.

**Comment by magarto** [comment]
Perfect, I will list them in a couple of hours.

**Comment by magarto** [comment]
**Tesla ovl:**
Edizon, sysmodue, status-monitor, fizeau, ldn_mitm, emuiibo and sys-clk

**Sysmodules:**
sys-ftp-light (disabled), sys-con (enabled), Fizeau (enabled), lnd_mitm (disabled), MissionControl (enabled), emuiibo (disabled)


Fizeau ony works after screen on just a few and random times.
RAM is only 361/4070 MB on home screen without games loaded.

**Comment by averne** [comment]
Hi, could you check if this also happens with the latest version?
https://github.com/averne/Fizeau/releases/tag/v2.4.0

**Comment by elayes211** [comment]
It happens to me as well, I have to enter into the applet, disable it and reenable it.

**Comment by averne** [comment]
> It happens to me as well, I have to enter into the applet, disable it and reenable it.

Can you please check that the line `active = true` isn't commented in your config?
Otherwise, can you please give some details about your setup.

**Comment by elayes211** [comment]
Sure, one moment!

**Comment by elayes211** [comment]
active            = true

handheld_profile  = profile1
docked_profile    = profile2

[profile1]
dusk_begin        = 21:00
dusk_end          = 21:30
dawn_begin        = 07:00
dawn_end          = 07:30
temperature_day   = 6500
temperature_night = 3000
filter_day        = none
filter_night      = none
brightness_day    = 1.000000
brightness_night  = 1.000000
gamma_day         = 1.840000
gamma_night       = 1.840000
saturation_day    = 1.000000
saturation_night  = 1.000000
luminance_day     = 0.000000
luminance_night   = -0.300000
range_day         = 0.00-1.00
range_night       = 0.00-1.00
dimming_timeout   = 05:00

[profile2]
dusk_begin        = 21:00
dusk_end          = 21:30
dawn_begin        = 07:00
dawn_end          = 07:30
temperature_day   = 6500
temperature_night = 3000
filter_day        = none
filter_night      = none
brightness_day    = 0.700000
brightness_night  = 0.300000
gamma_day         = 2.400000
gamma_night       = 2.400000
saturation_day    = 1.000000
saturation_night  = 1.000000
luminance_day     = 0.000000
luminance_night   = -0.300000
range_day         = 0.00-1.00
range_night       = 0.00-1.00
dimming_timeout   = 05:00

[profile3]
dusk_begin        = 21:00
dusk_end          = 21:30
dawn_begin        = 07:00
dawn_end          = 07:30
temperature_day   = 6500
temperature_night = 6500
filter_day        = none
filter_night      = none
brightness_day    = 1.000000
brightness_night  = 1.000000
gamma_day         = 2.400000
gamma_night       = 2.400000
saturation_day    = 1.000000
saturation_night  = 1.000000
luminance_day     = 0.000000
luminance_night   = 0.000000
range_day         = 0.00-1.00
range_night       = 0.00-1.00
dimming_timeout   = 05:00

[profile4]
dusk_begin        = 21:00
dusk_end          = 21:30
dawn_begin        = 07:00
dawn_end          = 07:30
temperature_day   = 6500
temperature_night = 6500
filter_day        = none
filter_night      = none
brightness_day    = 1.000000
brightness_night  = 1.000000
gamma_day         = 2.400000
gamma_night       = 2.400000
saturation_day    = 1.000000
saturation_night  = 1.000000
luminance_day     = 0.000000
luminance_night   = 0.000000
range_day         = 0.00-1.00
range_night       = 0.00-1.00
dimming_timeout   = 05:00

**Comment by averne** [comment]
I'm quite confused about this, to be honest...
Can you try to go in the system settings, toggle the "display color" setting with whatever?

**Comment by SSSHEFATH** [comment]
I suddenly started having this issue as well. I completely redid my Atmos folder, but to no avail. It worked fine for a week!

**Comment by averne** [comment]
> I suddenly started having this issue as well. I completely redid my Atmos folder, but to no avail. It worked fine for a week!

Hi, could you give more information about the state of the system when it occurs? Did the sysmodule crash (then please upload a crash report). You can check that it's still running with this https://github.com/WerWolv/Hekate-Toolbox/releases

**Comment by Medel87** [comment]
I have same problem, last version chailoader with last atmos, fizeau sysmodule is active on boot but always shows OFF, and must open overlay every time I screen off to activate it

**Comment by Patrickz22** [comment]
![IMG_20230823_144037](https://github.com/averne/Fizeau/assets/66673700/843df2e8-44e7-4f66-9ba1-42f193382274)
Im having the same problem..
