### ISSUE TITLE
Using Fizeau on the latest system will cause a crash

### ISSUE THREAD

**Issue by YunnXii** [averne/Fizeau#47]
Atmosphere 1.2.6 and HOS 13.2.1 ，installed with version 2.3.0 Fizeau and cannot enter the system.

**Comment by averne** [comment]
Hello, this works fine on my hardware so I assume something is wrong with your setup.
Do you have additional system modules installed?

**Comment by YunnXii** [comment]
Sorry，This problem is not just me. I saw a lot of discussions on a game forum that Fizeau can't be used on the latest system. I'll try again.

**Comment by averne** [comment]
Can you try this build?
[Fizeau-2.3.0-44c15a2.zip](https://github.com/averne/Fizeau/files/8288763/Fizeau-2.3.0-44c15a2.zip)
[Fizeau-chl-2.3.0-44c15a2.zip](https://github.com/averne/Fizeau/files/8288766/Fizeau-chl-2.3.0-44c15a2.zip)

**Comment by YunnXii** [comment]
Thank you! Although this version is still unable to enter NRO, it can realize its functions through Tesla

**Comment by carr654** [comment]
fine foe me on atmos 1.2.6 and firm 13.2.1 no issues at all
