### ISSUE TITLE
14.0.0 support

### ISSUE THREAD

**Issue by JrRadiant** [averne/Fizeau#48]
Dear @averne! 

Please do the support for FW 14.0.0, AMS 1.3.0.

Thank you VM in Advance!!!

**Comment by averne** [comment]
[71322a4](https://github.com/averne/Fizeau/commit/71322a41cb7c5b67527081adb470bfe26c1cb0dc) fixes the sysmodule.
14.0 maxes out lbl, the service used for backlight control. That means Fizeau can't connect do anything with backlight anymore.

I've disabled it temporarily, will look for a way to work around it.
The application is broken for some reason and I don't have time right now to debug it, so if you want to try the CI build be aware of that.

**Comment by lowburger** [comment]
> The application is broken for some reason and I don't have time right now to debug it, so if you want to try the CI build be aware of that. I'll do a release after it's fixed.

I try and homebrew and overlay loading, or you mean something else?

**Comment by ncend** [comment]
so, does it mean that the overlay still working? only the backlight adjustment doesn't work? but the color overlay works?

**Comment by averne** [comment]
> I try and homebrew and overlay loading, or you mean something else?

> so, does it mean that the overlay still working? only the backlight adjustment doesn't work? but the color overlay works?

The overlay works, not the .nro application.

And yeah, backlight control is broken for the time being, the rest (including luminance control) works as expected.

**Comment by lowburger** [comment]
> > I try and homebrew and overlay loading, or you mean something else?
> 
> > so, does it mean that the overlay still working? only the backlight adjustment doesn't work? but the color overlay works?
> 
> The overlay works, not the .nro application.

Yes I meaning nro working for me when I test. I don't changes any setting but nro open as normal.

Thx for update!

**Comment by lowburger** [comment]
> And yeah, backlight control is broken for the time being, the rest (including luminance control) works as expected.

Backlight it's possible for fix or can't bring it back?

**Comment by averne** [comment]
> Backlight it's possible for fix or can't bring it back?

Possible after Atmosphere made changes to accommodate for 14.0+ firmwares.

**Comment by lowburger** [comment]
Hi @averne 

I just tell you github action expire so there isn't official fizeau 14+ download available.

**Comment by conquelicot** [comment]
> > Backlight it's possible for fix or can't bring it back?
> 
> Possible after Atmosphere made changes to accommodate for 14.0+ firmwares.

Is it possible to check this one again once Atmosphere makes changes to accomodate for 15.0+ Firmware?

**Comment by averne** [comment]
Hi all, 
Can someone confirm that these work fine on 14.0.0+?
Backlight control is still disabled while I explore options to bring it back.
A couple of other issues have been fixed.
[Fizeau-2.3.1-25141ac.zip](https://github.com/averne/Fizeau/files/9909915/Fizeau-2.3.1-25141ac.zip)
[Fizeau-chl-2.3.1-25141ac.zip](https://github.com/averne/Fizeau/files/9909916/Fizeau-chl-2.3.1-25141ac.zip)

**Comment by siminles** [comment]
> Hi all, Can someone confirm that these work fine on 14.0.0+? Backlight control is still disabled while I explore options to bring it back. A couple of other issues have been fixed. [Fizeau-2.3.1-25dbcb7.zip](https://github.com/averne/Fizeau/files/9910275/Fizeau-2.3.1-25dbcb7.zip) [Fizeau-chl-2.3.1-25dbcb7.zip](https://github.com/averne/Fizeau/files/9910276/Fizeau-chl-2.3.1-25dbcb7.zip)

yes，work work fine on 15.0.0

**Comment by yemaowuxin** [comment]
> 

Work error on 15.0.1/AMS1.40. Error code: 2168-0001 (0x2a8). I don't know way.
