### ISSUE TITLE
"Correction active" toggle results in freeze and crash on latest version

### ISSUE THREAD

**Issue by pixeltester** [averne/Fizeau#51]
I'm experiencing the following freeze and crash with the latest commit of Fizeau:

Console and environment: Switch Lite (Mariko), atmosphere 1.3.2, firmware 14.1.1
Sysmodules: Tesla + Fizeau

The console freezes then reboots when selecting the "Correction active" toggle in either the overlay or the homebrew. I also use Tesla on an Erista console and this does not happen there, so it seems to be a hardware specific issue? Also to note that Fizeau works normally otherwise, just that the toggle triggers the crash.

These crash and fatal reports are generated:
https://gist.github.com/pixeltester/03f9ec8dfdce71756b5075b510e3d9b4

**Comment by ponymuch** [comment]
Same Question, Switch Lite Version.

**Comment by pixeltester** [comment]
> Same Question, Switch Lite Version.

I'm not sure if averne is active at the moment. I'm still using the chainloader version which works, you just have to remember not to touch the "Correction active" toggle.

**Comment by pixeltester** [comment]
I was able to check this on another Mariko console, seems to be exclusively a Switch Lite issue.

**Comment by averne** [comment]
Hi, can someone give these a try and confirm whether this problem is fixed?
[Fizeau-chl-2.3.1-25141ac.zip](https://github.com/averne/Fizeau/files/9909881/Fizeau-chl-2.3.1-25141ac.zip)
[Fizeau-2.3.1-25141ac.zip](https://github.com/averne/Fizeau/files/9909880/Fizeau-2.3.1-25141ac.zip)

**Comment by pixeltester** [comment]
@averne Just tested it and I can confirm that it's fixed, thanks!

**Comment by averne** [comment]
> Could you explain why this only happened on the Lite model?

https://github.com/averne/Fizeau/blob/master/sysmodule/src/nvdisp.cpp#L82
I try to set something on the external screen, however lite units don't have the corresponding hardware and nvidia's driver crashes instead of returning an error
