### ISSUE TITLE
Can't undim after timeout dim

### ISSUE THREAD

**Issue by orbitinstasis** [averne/Fizeau#57]
Hi, great software, thank you.

I've noticed on my system 15.0.1, using the non overlay version 2.4.0 4b55d12 when the dim timeout is reached, the screen doesn't undim itself until I go into the app. Is this a bug?

**Comment by averne** [comment]
Hi,
On 15.0 the dimming isn't managed by the app but by the OS, so it should have the default behavior as configured in your settings. Do you have it enabled?

**Comment by orbitinstasis** [comment]
> Hi, On 15.0 the dimming isn't managed by the app but by the OS, so it should have the default behavior as configured in your settings. Do you have it enabled?

Yup when it's enabled in the OS it dims as expected, but it doesn't undim until i enter the Fizeau applet or re-activate fizeau from the overlay.

**Comment by Haniasita** [comment]
I second this, I'm experiencing the same behavior when my Switch is docked. Whenever the screen dims, it undims for half a second then dims again until I enter the Fizeau app. It only happens when Fizeau is enabled.

**Comment by MultiKoopa** [comment]
> I second this, I'm experiencing the same behavior when my Switch is docked, using the overlay version of 2.4.0 Fizeau. Whenever the screen dims and I touch the controller, it undims for half a second then dims again until I enter the Fizeau app. It only happens when Fizeau is enabled.
> 
> Similarly, disabling the Fizeau overlay for me, also swaps the console's dimming with whatever settings Fizeau had (Meaning instead of dimming, the orange-colored settings I had show up instead). Disabling the sysmodule entirely fixes this.
> 
> Using an unpatched Switch, running HOS 15.0.1 and Atmosphere 1.4.0

same exact thing happens to me when docked; HOS 16.0.2, Atmosphere 1.5.3

**Comment by averne** [comment]
This should be fixed by the latest release: https://github.com/averne/Fizeau/releases/tag/2.4.3
