### ISSUE TITLE
Issue with 16.0.3

### ISSUE THREAD

**Issue by MercurioX85** [averne/Fizeau#63]
with 16.0.3 when I activate the overlay the display changes are successful, but when I try to deactivate, the changes remain active.  With a downgrade to 16.0.2 everything works again.

**Comment by averne** [comment]
Hi,

Please make sure everything is fine in our setup. 16.0.3 works fine for me, and this update didn't really change anything: https://switchbrew.org/wiki/16.0.3

**Comment by Roigar** [comment]
Can confirm it works with 16.1.0

**Comment by averne** [comment]
Tested working on up to 17.0
