### ISSUE TITLE
[RESOLVED]

### ISSUE THREAD

**Issue by JrRadiant** [averne/Fizeau#64]
Hello, dear Averne!..

Got this error when trying to run latest 2.4.1-680ba4f Fizeau build with FW 16.1.0, AMS 1.5.5:
![error](https://github.com/averne/Fizeau/assets/61790774/269b2450-3fb5-4b31-a3bc-f75deca59c53)

**Comment by MultiKoopa** [comment]
Strange. I'm also on 16.1.0/1.5.5, no issues here. Are you also using latest Hekate 6.0.6? Not sure how that could cause an issue with Fizeau, but...

**Comment by JrRadiant** [comment]
Ohhh my bad, after reinstalling the module now it works good, thank you @MultiKoopa !
