### ISSUE TITLE
Game profiling

### ISSUE THREAD

**Issue by mightysashiman** [averne/Fizeau#68]
Since all game are not equally as good at doing good colour grading depending on the hardware’s gamut (non-OLED vs OLED),I suggest the following (major) improvement to this already awesome utility:
1) add profile creation/deletion/switch within the fizeau overlay
2) enable creating a profile for a specific game, with ability to auto load that game-specific profile.

More than willing to help test
Thanks in advance!

**Comment by averne** [comment]
Hi, at the moment I'm not interested in working on this feature, but I would accept a pull request.
You can use profiles to quickly switch between presets.
