### ISSUE TITLE
Fails to start on 10.0.2

### ISSUE THREAD

**Issue by psyfl** [averne/Fizeau#7]
Crashes immediately on 10.0.2

**Comment by averne** [comment]
Works for me on 10.0.2|AMS 0.11.1|S.
Can you give me more detail on your setup ? (CFW version, sysnand/emunand, other sysmodules active)

**Comment by psyfl** [comment]
I'm using Atmosphere 0.12.0 on emuMMC. Error code 2345-0038 (0x4d59).

**Comment by averne** [comment]
Any other sysmodules running? Fyi this is `LibnxError_InitFail_Time`, which means time sessions might get exhausted by other programs.

**Comment by psyfl** [comment]
Found out that its a conflict with sys-clk.

**Comment by psyfl** [comment]
Seems to have been a conflict with sys-clk.

**Comment by averne** [comment]
Good to know. Keeping this open for the time being, I'll see if it's possible to work around this.

**Comment by averne** [comment]
This should be fixed by a1e79c0fbe9a5841b5c1ce2c831d83a134787aad, where the time is queried once then deduced using ticks.
