### ISSUE TITLE
[Question] Fizeau for CFW Ver 17.0.1

### ISSUE THREAD

**Issue by kietdev1** [averne/Fizeau#71]
Hi, Can it work for CFW ver 17.0.1. And I have some questions?
- This is same as Night light (Windows), and Night shift (iOS) functionality.
- Can we uninstall when we not longer use ?
Thanks

**Comment by averne** [comment]
>  Can it work for CFW ver 17.0.1

Yes, though I recommend using these builds until I do a new release.
https://gbatemp.net/attachments/fizeau-2-4-2-19a25f5-dirty-zip.409789/
https://gbatemp.net/attachments/fizeau-chl-2-4-2-19a25f5-dirty-zip.409790/

> This is same as Night light (Windows), and Night shift (iOS) functionality.

Yeah essentially.

> Can we uninstall when we not longer use ?

Of course, just remove the files from your sd.

**Comment by kietdev1** [comment]
Thank you so much. I'm copy and turn on CFW. It works properly.
Additional:
Will Auto brightness of settings use both Fizeau in future?

**Comment by averne** [comment]
Brightness control used to work but was removed a while ago because of OS changes that did not permit it.
