### ISSUE TITLE
Lag bug in 2.4.3

### ISSUE THREAD

**Issue by cucholix** [averne/Fizeau#72]
There’s a bug in 2.4.3 where the whole system become super laggy, I'm not sure how exactly trigger, seems random, the last time it happened my Switch was sleeping in the dock, I pick it up to play in handheld and the system becomes laggy, only has happened on handheld mode so far.

During the issue those are the CPU readings
in handheld:
Core#3: 70-99%
Core#0 and #2: 4-50%
Core#1: 4-12% 

Latest atmosphere and system fw as January 10, 2024

**Comment by averne** [comment]
Thanks for the report.
Those cpu readings look a bit weird. Fizeau, just like every other system component, runs only on core 3. So if it was sent looping due to some bug, that shouldn't affect cores 0-2. 
Were you in a game or in the home menu when the bug triggered?

**Comment by cucholix** [comment]
I was in the screen where it ask to press 3 times the same button to unlock the system, from there and during home menu everything is laggy at the point it's hard to the system respond to button press inputs

**Comment by abelmarkus** [comment]
Same to me: Fizeau activated, Switch sleeping into the dock then i take it and system responsiveness is totally slow.
Installed chianloader version 2.4.3, atmos 1.6.2, hos 17.0.0

**Comment by darkjeann** [comment]
Sadly the same problem also happens to me, I have everything updated to 17.0.1 os, HB 17.0.0

**Comment by biase-d** [comment]
I got the same problem (2.4.3-438ffd6 chainloader version)

The trigger so far has been putting console to sleep while in handheld then docking it and if you do the reverse same bug occurs

CPU usage skyrockets making the system super slow till you turn deactivate Fizeau 

The solution thus far has been deactivating fizeau before putting console to sleep when you want to either dock or undock it

**Comment by cuong-tech** [comment]
I also got the same problem on latest Switch firmware 17.0.1 + Atmosphere 1.6.2 + Hekate 6.1.0

It has already happened several times when I removed the Switch from the dock while it was sleeping.

@averne any chance you could look into it?

**Comment by Starwarsfan2099** [comment]
Same here, Atmosphere 1.6.2, firmware 16.0.3, Hekate 6.1.0, Fizeau 2.4.3 installed from GitHub and not hbstore. Happens often if the Switch is sleeping on the dock, Fizeau is active, and then removed from the dock. Doesn't matter if a game is running or not. Everything runs super slowly until Fizeau is toggled to inactive via Tesla.

**Comment by febritecno** [comment]
this problem also happened to me. when I was in dock mode then unplugged it and switched to handheld mode. the display immediately crashed and broke.

**Comment by averne** [comment]
This should be fixed in 2.5.0: https://github.com/averne/Fizeau/releases/download/v2.5.0/Fizeau-2.5.0-37c07cd.zip
