### ISSUE TITLE
Not yet working 

### ISSUE THREAD

**Issue by Blacknife420** [averne/Fizeau#74]
Hi I'm on the latest firmware 17.0.1 and atmosphere and it's not yet working for me

**Comment by Blacknife420** [comment]
Running 17.0.1 [ams and 1.6.2[E and my nx ovlloader (tesla menu) is v1.0.6
everything I bleave is up to date but get this error

**Comment by averne** [comment]
Are you using the chainloader version? Any other sysmodules installed ?How does the error manifest? Does it crash the whole console? Does it just not start? Do you get a specific error code?
Again, I need details if you want me to help.

**Comment by Blacknife420** [comment]
I sent a image with the error message I get it only give me the error when
opened from the hb menu it doesn't crash the whole console it won't open in
tesla I have got other sys modules like emuiibo idk what one I have
installed witch one should I installed and error  is error: 0x1 (2001-0000)

**Comment by Blacknife420** [comment]
I downloaded the one in the hb store

**Comment by averne** [comment]
Please install from the github repository, check that files are correctly installed in the /atmosphere/contents folder, and reboot.

**Comment by Blacknife420** [comment]
What one do I get  fizeau or fizeau chl

**Comment by averne** [comment]
Get chl

**Comment by Blacknife420** [comment]
Sweet will try now and let you know

**Comment by Blacknife420** [comment]
Alsome idk how but it fixed it thank you

**Comment by averne** [comment]
Probably missing reboot

**Comment by Blacknife420** [comment]
Na I didn't when I last tried to reboot the contacts files for it was
keeping me from getting into cwf thay made it crash coz I tryed the other
one then tryed chained then tryed the one on app store all would fail at
reboot so had to delete those 2 files to be able to boot but this time it
works thank you

**Comment by vgmoose** [comment]
@Blacknife420 What do you mean by "contacts files"? Which two files did you have to delete to get it working?

**Comment by Blacknife420** [comment]
The 2 files in contents and no not to get it working its working fine now
with them I was haven a issue where but thay were makeing me have a issue
were it would let me get into cfw before I put the issue out

**Comment by Blacknife420** [comment]
But not having it now I working fine
