### ISSUE TITLE
Overlay menu doesn’t work on the latest update 17.0.1 

### ISSUE THREAD

**Issue by notoriousbiggie** [averne/Fizeau#75]

**Comment by averne** [comment]
Please provide details, because it works on my machine.

**Comment by notoriousbiggie** [comment]
installed Fizeau and both both tesla and ovlloader 
restarted the console and for some reason it doesn’t show on the tesla menu

![IMG_0485](https://github.com/averne/Fizeau/assets/47916832/3eef2eec-02eb-43f3-9109-538c2cfb7baf)
  
![IMG_0484](https://github.com/averne/Fizeau/assets/47916832/539b7532-32d5-468d-833b-6a40cd97bcdb)

**Comment by averne** [comment]
Install Fizeau manually from the github release and make sure Fizeau.ovl is in the /switch/.overlays folder.

**Comment by notoriousbiggie** [comment]
Where can i find the .ovl file ? it's not included in the zip files

**Comment by averne** [comment]
It is in the zip, in /switch/.overlays.

**Comment by notoriousbiggie** [comment]
well im an idiot, the .overlay folder was hidden i had to show hidden files on the mac. thank you and sorry for bothering.
