### ISSUE TITLE
Fizeau Chainloader Fatal Error

### ISSUE THREAD

**Issue by Starwarsfan2099** [averne/Fizeau#76]
Greetings! Thank you so much for this tool! I attempted to install the latest chainloader version (`2.4.3`, from Github, not hbstore) and it crashes when loading Atmosphere with this error:

```
A fatal error occurred when running Atmosphere.
Program ID: 0100000000000F12
Error Desc: std::abort() called (0xffe)
```
`report_000000000da8d561.bin` is the report for this error and is attached to this issue in a zip file. ([reports.zip](https://github.com/averne/Fizeau/files/14501532/reports.zip))

Version information:

- Atmosphere: 1.6.2
- Firmware: 16.0.3
- Hekate: 6.1.0

Also to note, after deleting `contents/0100000000000F12`, the same crash happens again with `010000000000CF12`, same error. That report (`report_000000000c5514a3.bin`) is also attached, but I wasn't sure if that crash just occurs from deleting the first folder.

**Comment by averne** [comment]
Hi, please check that the files are correctly set up, especially if you installed from a 3rd party shop such as the homebrew appstore.
In addition please run the hekate archive bit fixer.

**Comment by Starwarsfan2099** [comment]
Files were correct and from the GitHub, but I didn't even think to try Archive Bit Fixer, that fixed it. Thanks.
