### ISSUE TITLE
fizeau crashing upon opening applet mode of hbmenu

### ISSUE THREAD

**Issue by Nrazuke** [averne/Fizeau#78]
when im on a game and i tried opening applet mode of hbmenu it becomes unresponsive and if you tried exiting it will become just a gray screen

**Comment by Nrazuke** [comment]
nevermind, it was another module that was causing the problem

**Comment by Nrazuke** [comment]
actually when i deleted fizeau it worked like magic now i dont know if its a bug with fizeau not updating or what

**Comment by averne** [comment]
Please reopen if this problem happens in 2.5.0: https://github.com/averne/Fizeau/releases/download/v2.5.0/Fizeau-2.5.0-37c07cd.zip
