### ISSUE TITLE
Settings will not be saved

### ISSUE THREAD

**Issue by seavers11** [averne/Fizeau#79]
When i change settings and press aplly, close the app and start it again, my changes will not be safed

**Comment by averne** [comment]
Try to clear archive bits from hekate before anything.

Also could you post some more information? Details about your setup (Hardware model, AMS/firmware version, other sysmodules installed)

**Comment by seavers11** [comment]
I clear the archive bits but nothing has changed.
My Switch is the v1 model, with the newest AMS and FW 18.0.1, sysmodules are EdiZon,ldn_mitm,Emuiibo,Fizeau,QuickNTP,Sysmodules,sys-patch.

**Comment by averne** [comment]
Can you try to disable other sysmodules and confirm whether this behavior still happens?

**Comment by Mraulio** [comment]
I also have this issue, both using Fizeau directly or Tesla overlay, you can apply the settings but every time you open it, it sets and applies the default values. My Switch, Atmosphere and modules are up to date.
And if you use the overlay after boot without opening Fizeau normally, it crashes and Fizeau shows an error too (see images).
![Home_Menu_20240521_191721_00](https://github.com/averne/Fizeau/assets/12874082/bcc01e53-9c8b-4ba8-a426-1222d08f8cfa)
![Album_20240521_191933_00](https://github.com/averne/Fizeau/assets/12874082/b5cf8fe0-2db1-40c0-8904-97d7edd90e74)

**Comment by averne** [comment]
> I also have this issue, both using Fizeau directly or Tesla overlay, you can apply the settings but every time you open it, it sets and applies the default values. My Switch, Atmosphere and modules are up to date. And if you use the overlay after boot without opening Fizeau normally, it crashes and Fizeau shows an error too (see images). ![Home_Menu_20240521_191721_00](https://private-user-images.githubusercontent.com/12874082/332526160-bcc01e53-9c8b-4ba8-a426-1222d08f8cfa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTU1MDcsIm5iZiI6MTcxNjMxNTIwNywicGF0aCI6Ii8xMjg3NDA4Mi8zMzI1MjYxNjAtYmNjMDFlNTMtOWM4Yi00YmE4LWE0MjYtMTIyMmQwOGY4Y2ZhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE4MTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MWRmMmQyMGZmMTUyNzRiYTgzNzE3YmFmY2IxZGUyYjE2ZWIzNTQwYTNjYmI1MGQyZThhNDg3OWQzNDVlNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qa3nPUuSFuKfy8zgg0tWNoHkotAqu1wmRWqAkgRNJPs) ![Album_20240521_191933_00](https://private-user-images.githubusercontent.com/12874082/332526176-b5cf8fe0-2db1-40c0-8904-97d7edd90e74.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTU1MDcsIm5iZiI6MTcxNjMxNTIwNywicGF0aCI6Ii8xMjg3NDA4Mi8zMzI1MjYxNzYtYjVjZjhmZTAtMmRiMS00MGMwLTg5MDQtOTdkN2VkZDkwZTc0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE4MTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiM2I2ZmNmZGUzNzM2YzViY2YyOTdjN2YxMWVlMmU2N2Q0OTM5NjlkOGJlN2E5NmMxMGRkNDgyYzgyODRmNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.awmDViR082qDr7DfK4F-8uSdFN2L8QX5_NgQ7mwCbc4)

Both of these things definitely work for me. 
Could you post your config here? And are you using windows? I'm thinking it might be a problem with line endings.
Also, you can try to delete your config file, then use the default one from the release without opening it in a text editor.

**Comment by averne** [comment]
I think I fixed the problem: [Fizeau-2.5.0-37c07cd-dirty.zip](https://github.com/averne/Fizeau/files/15395180/Fizeau-2.5.0-37c07cd-dirty.zip)
Can you try the above and confirm? Make sure your config file does not contain brightness settings (the easiest way is to overwrite it with the one that is bundled in the zip).

**Comment by seavers11** [comment]
THX works perfect now

**Comment by Mraulio** [comment]
Works perfect for me now too, including docking and the Tesla overlay. Thanks a lot!
