### ISSUE TITLE
version 2.5.1 crashes 

### ISSUE THREAD

**Issue by RandomName000001** [averne/Fizeau#81]
Hello, version 2.5.1 crashes and cannot be used. After testing, the other versions are normal, please fix it as soon as possible, thank you!

**Comment by averne** [comment]
Reopen once you have provided actionable information (firmware/ams version, console type, other sysmodules running). 
Please also post your config.

**Comment by RandomName000001** [comment]
The application crashes, the real system version 18.0.1, the Atmosphère system version 1.7.0, the same environment, the 2.5.0 version works fine. Version 2.5.1 The program directly crashes when opened, prompting me to restart or let me upgrade CFW.

**Comment by RandomName000001** [comment]
The Switch machine is a battery version.

**Comment by averne** [comment]
Can you upload your config file here? Given that the application works for me and many other people, I have to assume that something is wrong with your setup.

**Comment by RandomName000001** [comment]
Which config file, all my other programs are normal, even I use Fizeau 2.5.0 version without problems, Fizeau 2.5.1 crashes when I open the program.

**Comment by averne** [comment]
It's either at /switch/Fizeau/config.ini or /config/Fizeau/config.ini

**Comment by RandomName000001** [comment]
I didn't make any manual modifications to these configuration files, they were all downloaded directly from GitHub, and the program could not be started directly, and the crash was reported.I downloaded version 2.5.0 and version 2.4.3 with the same operation, and I was able to open the program and use it normally.

**Comment by RandomName000001** [comment]
Version 2.5.1 crashed directly when opened, I didn't have a chance to modify any configuration options at all, and when I installed the software, I didn't manually modify any configuration options, it was the original file downloaded from GitHub.

**Comment by averne** [comment]
I just tried 2.5.1 with default config, it works fine.
I am once again asking for you to upload your configuration file.
