### ISSUE TITLE
Error: 0x1 (2001-0000)

### ISSUE THREAD

**Issue by LCrizostimo** [averne/Fizeau#82]
Fizeau version 2.5.1
![20240601_212932](https://github.com/averne/Fizeau/assets/171458866/f5a037a0-d58a-4f70-ac4b-708901fb06bb)
Nintendo switch V1
V: 18.0.1

English:
"Fizeau doesn't open, even after restarting the console. Can someone help me?"

Português:
 Fizeau não abre, mesmo após reiniciar o console. Alguém pode me ajudar?

**Comment by averne** [comment]
This means the sysmodule is not running. Check that all the files are correctly installed, and also run the archive bit fixer from hekate.

**Comment by SiTWulf** [comment]
Same issue for me.
Firmware 1.18.0
Atmo: 1.7.0 (Full release)

Executed the archive bit fixer from hekate without any luck

**Comment by averne** [comment]
Can you post your config file?

**Comment by SiTWulf** [comment]
Not touched config.
Fizeau don't open
[config.zip](https://github.com/user-attachments/files/15539068/config.zip)

**Comment by LCrizostimo** [comment]
> Isso significa que o sysmodule não está em execução. Verifique se todos os arquivos estão instalados corretamente e execute também o fixador de bits de arquivo do hekate.

Como executo esse fixador de bits?

**Comment by averne** [comment]
Please communicate in english and look this up for yourself. This is not a switch hacking support forum.
