### ISSUE TITLE
support for 18.1 ?

### ISSUE THREAD

**Issue by mickaelandrieu** [averne/Fizeau#84]
Hi @averne,
Since I've updated CFW to 18.1, fizeau module is not working anymore : do you plan to work on the support of the latest version ?

**Comment by averne** [comment]
Hi, I can confirm that 18.1+AMS1.7.1 works for me and has been working for a while.

**Comment by mickaelandrieu** [comment]
Yes, just noticed I was still on 2.5.1.
Just upgraded to 2.5.3, then reboot, then works like a charm !

Thank you for this module :)
