### ISSUE TITLE
Have to open overlay to re-enable Fizeau each time after turning off screen (only during the day)

### ISSUE THREAD

**Issue by smobanan** [averne/Fizeau#87]
Hi, so I saw that people had similar issues with Fizeau on older versions (#73 ), I have the same thing on the latest version. However, at night that is not the case; this only happens during the day, weirdly. active = true is set. in /config/Fizeau/config.ini

**Comment by averne** [comment]
Can you post some details regarding your setup?
AMS/FW version, other sysmodules running. Also please upload your config file here.

**Comment by smobanan** [comment]
yeah sure, so im on AMS 1.7.1 and my FW is 18.1.0
i'm also using a V2 / Mariko Switch, if that matters

here's my config.ini:
```
active            = true

handheld_profile  = profile1
docked_profile    = profile2

[profile1]
dusk_begin        = 21:00
dusk_end          = 21:30
dawn_begin        = 07:00
dawn_end          = 07:30
temperature_day   = 6500
temperature_night = 3310
filter_day        = none
filter_night      = none
gamma_day         = 1.850000
gamma_night       = 1.850000
saturation_day    = 1.000000
saturation_night  = 1.000000
luminance_day     = 0.000000
luminance_night   = 0.000000
range_day         = 0.00-1.00
range_night       = 0.00-1.00
dimming_timeout   = 05:00

[profile2]
dusk_begin        = 21:00
dusk_end          = 21:30
dawn_begin        = 07:00
dawn_end          = 07:30
temperature_day   = 6500
temperature_night = 3310
filter_day        = none
filter_night      = none
gamma_day         = 2.400000
gamma_night       = 2.400000
saturation_day    = 1.000000
saturation_night  = 1.000000
luminance_day     = 0.000000
luminance_night   = 0.000000
range_day         = 0.00-1.00
range_night       = 0.00-1.00
dimming_timeout   = 05:00

[profile3]
dusk_begin        = 00:00
dusk_end          = 00:00
dawn_begin        = 00:00
dawn_end          = 00:00
temperature_day   = 6500
temperature_night = 6500
filter_day        = none
filter_night      = none
gamma_day         = 2.400000
gamma_night       = 2.400000
saturation_day    = 1.000000
saturation_night  = 1.000000
luminance_day     = 0.000000
luminance_night   = 0.000000
range_day         = 0.00-1.00
range_night       = 0.00-1.00
dimming_timeout   = 00:00

[profile4]
dusk_begin        = 00:00
dusk_end          = 00:00
dawn_begin        = 00:00
dawn_end          = 00:00
temperature_day   = 6500
temperature_night = 6500
filter_day        = none
filter_night      = none
gamma_day         = 2.400000
gamma_night       = 2.400000
saturation_day    = 1.000000
saturation_night  = 1.000000
luminance_day     = 0.000000
luminance_night   = 0.000000
range_day         = 0.00-1.00
range_night       = 0.00-1.00
dimming_timeout   = 00:00
```

**Comment by smobanan** [comment]
oh yeah, sorry i forgot the sysmodules;
i have sys-patch, sys-con, emuiibo, saltynx, sysdvr and or course fizeau running

**Comment by averne** [comment]
Thanks for the info, I was able to reproduce the issue.
Can you confirm that the build below fixes the problem, in handheld and docked mode? 
Thanks.

[Fizeau-2.5.4-1afd41b.zip](https://github.com/user-attachments/files/16565083/Fizeau-2.5.4-1afd41b.zip)

**Comment by smobanan** [comment]
yeah, that build works for me, thanks :)

**Comment by averne** [comment]
Were you able to test in docked mode? I don't have access to a tv at the moment, so it would be nice to get confirmation before doing a release.

**Comment by smobanan** [comment]
yeah, that build fixes the issue.
however, you need to reopen the overlay when switching from docked to handheld, so not fully id say

**Comment by averne** [comment]
I decided to stop trying to detect when the system changed the color correction configuration, and just disable Nintendo's access. The [new release](https://github.com/averne/Fizeau/releases/tag/v2.5.4) includes binary patches for nvnflinger to this effect, that should fix conflicts for good, however they will need to be re-generated after each system update.
