### ISSUE TITLE
Fizeau app takes too long to turn off/rebooot, more details in the desc.

### ISSUE THREAD

**Issue by julioSantosAlbarregas** [averne/Fizeau#88]
I've just installed Fizeau and made some screen tweaks, everything fine but somehow if the app is running in the background, turning off the switch or trying to reboot takes way too long than normal.

I've used tesla menu and sysmodules to disable it and it now takes like 5 seconds to reboot/turn off, which is the expected behaviour.

`(Edited comment)`

**Comment by averne** [comment]
So let me get this straight, you mean that the console doesn't power off completely? 
Do you have autorcm enabled? What you describe sounds like intended behavior with it on.

Also can you post your config here so I can try to reproduce? Thanks.

**Comment by julioSantosAlbarregas** [comment]
Ok I was about to write down a comment and record a video of what happens and I've noticed it actually turns off/reboot but it takes like 10 times more time than if I turn off/reboot from HOS:

I measured the time and it takes about 5-7 seconds to reboot from OFW and nearly 50 seconds to reboot from CFW Atmosphere, only if Fizeau app is running in the background, if I disable it from the tesla overlay menu it takes the same amount of seconds like OFW, around 5-7.
OFW Vídeo -> https://imgur.com/a/dHDAy1Y
CFW Fizeau disabled -> https://imgur.com/a/h5eqMQQ
CFW Fizeau enabled -> https://imgur.com/a/L0xWQuP

I don't think autorcm is enabled because it is a v2 model so I don't need rcm mode at all, (at least for now, I'm very new to this modding switch world).

And the config you mentioned, do you mean the fizeau profile I'm using? If so here it is: Temp -> 6500k, Brightness -> 1.00, Gamma -> 1.95, Saturation -> 1.00 and Luminance -> 0.25, Color range -> full
If you mean other config please let me know which one and I'll post asap.

**Comment by averne** [comment]
Yes please upload your whole config.ini here, it's easier for me.

**Comment by julioSantosAlbarregas** [comment]
[config.zip](https://github.com/user-attachments/files/16942252/config.zip)

Here you have it, although it happens regardless of the config, just the app being in the background causes this issue.

**Comment by averne** [comment]
Uncomment `active = true` (remove the `;` at the start of the line), see if that fixes it?

**Comment by julioSantosAlbarregas** [comment]
Somehow if I uncomment that line it takes now twice as long as before... 2 minutes aprox I measured.

**Comment by averne** [comment]
Could you give this build a try, I believe I've fixed it, thanks.
[Fizeau-2.5.4-93e114b-dirty.zip](https://github.com/user-attachments/files/17003454/Fizeau-2.5.4-93e114b-dirty.zip)

**Comment by julioSantosAlbarregas** [comment]
It now works flawlessly, thank you very much!

**Comment by averne** [comment]
> Asking just out of curiosity, what was causing the issue?

I use mmio to detect changes in the color correction configuration. But when the displays are offline (for instance because the system is shutting down), these register reads hang, which in turn hangs the whole system.
I was formerly trying to prevent this by using a system functionality that notifies of status changes in various components, including display. However it appears that the nvidia code responsible for triggering this notification never does, or does it too late. So I switched to just checking if the display engines are powered on via yet another mmio region.
