### ISSUE TITLE
Sync ReverseNX Mode

### ISSUE THREAD

**Issue by g1nt0** [averne/Fizeau#92]
Currently, Fizeau does not recognize the docked/handheld state enabled through ReverseNX (https://github.com/masagrator/ReverseNX-Tool).

Sys-clk-OC (https://github.com/rashevskyv/sys-clk-OC) , for example, can do this:
![image](https://github.com/user-attachments/assets/d5425147-5274-4a1c-a98d-bf8f0176e55c)

This behavior could potentially be reproduced based on their sources (https://github.com/search?q=repo%3Arashevskyv%2Fsys-clk-OC%20reversenx&type=code).

**Comment by averne** [comment]
I don't see why this behavior would be desirable. Even if you pretending to be docked, you're still playing on the Switch handheld screen which has very different characteristics from whatever screen would be connected to your dock.

**Comment by g1nt0** [comment]
Since the Switch doesn’t support per-application brightness settings, I’m using Fizeau (with a red overlay) to reduce OLED burn-in risk in apps that block standby mode, such as during a long MTP session in DBI at high brightness (https://github.com/rashevskyv/dbi/issues/386) . This could also be implemented in Fizeau by enabling profile binding for individual applications.

**Comment by averne** [comment]
The intended way of having per-application settings is to switch between profiles manually.
Also what you should be using is a low luminance, a red tint doesn't help much for burn-in prevention.
